@startuml
'https://plantuml.com/class-diagram
class ActorDto {
	+ String getName()
	+ int getId()
	+ double getPopularity()
	+ Optional<String> getCharacter()
}

class TvSeriesDto {
	+ LocalDate getStartDate() {
	+ String getName()
	+ int getId()
	+ double getPopularity()
	+ int[] getGenreIds()
	+ Optional<String> getCharacter()

}

class GenreDto {
	+int getId()
	+ String getName()
}

@enduml